kind: pipeline
type: docker
name: build
steps:
- name: 检测代码
 image: rust:1.64.0-bullseye
 volumes:
  - name: cache
    path: /git
 commands:
  - mkdir /git/work
  - cd /git/work
  - git clone https://github.com/20020314/ward.git
steps:
- name: 编译
  image: maven:3.8.6-openjdk-18-slim
  volumes:
  - name: cache
    path: /git
 commands:
  - cd /git/work/ward
  - mvn clean package
- name: 上传
  image: plugins/s3
  settings:
    endpoint: https://oss.elysia.li
    bucket: lin-data
    access_key: EFE37X4BY84SCMFQWUZG
    secret_key: jm3aIfj3hq5oeAd6YTNnsVOEVQMf2B+J2rLUlGTS
    source: /drone/src/.git/*.jar
    target: /autobuild/
volumes:
- name: cache
  temp: {}
