kind: pipeline
type: docker
name: 编译jar

steps:
- name: 创建工作目录
  image: rust:1.64.0-bullseye
  volumes:
  - name: cache
    path: /jar
  commands:
  - cd /jar
  - git clone https://github.com/Rudolf-Barbu/Ward.git

- name: 编译
  image: maven
  volumes:
  - name: cache
    path: /jar
  commands:
  - cd /jar/ward
  - mvn clean package

- name: 上传
  image: plugins/s3
  settings:
    endpoint: https://oss.elysia.li
    bucket: lin-data
    access_key: EFE37X4BY84SCMFQWUZG
    secret_key: jm3aIfj3hq5oeAd6YTNnsVOEVQMf2B+J2rLUlGTS
    source: /drone/src/.git/*.jar
    target: /autobuild/
volumes:
- name: cache
  temp: {}
