kind: pipeline
type: docker
name: build
steps:
- name: 拉取代码
  image: rust:1.64.0-bullseye
  volumes:
  - name: cache
    path: /work
  commands:
  - cd /drone/src/.git/
  - ls -l
  - git clone https://github.com/20020314/Ward.git
  - echo "代码拉取完成"
steps:
- name: 编译
  image: maven:3.8.6-eclipse-temurin-8-alpine
  commands:
  - cd /drone/src/.git/
  - mvn clean package
- name: 上传
  image: plugins/s3
  settings:
    endpoint: https://oss.elysia.li
    bucket: lin-data
    access_key: EFE37X4BY84SCMFQWUZG
    secret_key: jm3aIfj3hq5oeAd6YTNnsVOEVQMf2B+J2rLUlGTS
    source: work/Ward/*.jar
    target: /autobuild/
volumes:
- name: cache
  temp: {}
