kind: pipeline
type: docker
name: build
steps:
- name: 检测代码
  image: rust:1.64.0-bullseye
  commands:
  - cd /drone/src/.git/

steps:
- name: 编译
  image: tomcat:9.0.68-jre8
  commands:
  - cd /drone/src/.git/
  - mvn clean package
- name: 上传
  image: plugins/s3
  settings:
    endpoint: https://oss.elysia.li
    bucket: lin-data
    access_key: EFE37X4BY84SCMFQWUZG
    secret_key: jm3aIfj3hq5oeAd6YTNnsVOEVQMf2B+J2rLUlGTS
    source: /drone/src/.git/*.jar
    target: /autobuild/
