kind: pipeline
type: docker
name: build

- name: 构建镜像
  image: plugins/docker
  volumes:
  - name: docker
    path: /var/run/docker.sock
  settings:
    repo: lin
    registry: registry
    tags: ${DRONE_BUILD_NUMBER}
