name: Drone CI

kind: pipeline

type: docker

trigger:

branch:

- master

steps:

name: Checkout repository

image: alpine/git

commands:

git clone ${DRONE_REPO}

cd ${DRONE_REPO_NAME}

name: Build with Java 11 and Ant

image: adoptopenjdk/openjdk11:alpine

commands:

apk add --no-cache ant

ant -noinput -buildfile build.xml
